FileTransferSite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('fileTransfer/', include('fileTransfer.urls')),
    path('admin/', admin.site.urls),
]

# When deployed, static files should be stored and served on a dedicated server
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fileTransfer/urls.py
from django.urls import path, include, reverse_lazy, re_path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'file_transfer'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('upload/', views.FileUpload.as_view(), name='upload'),
    path('files/', views.FileList.as_view(), name='file_list'),
    path('files/<int:pk>', views.DeleteFile.as_view(), name='delete_file'),
    re_path('files/(?P<signed_pk>[0-9]+/[A-Za-z0-9_=-]+)/$', views.SingleFile.as_view(), name='single_file'),
    path('signup/', views.SignUp.as_view(), name='sign_up'),
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('file_transfer:password_change_done')), name='password_change'),
    path('accounts/', include('django.contrib.auth.urls')),
]

fileTransfer/models.py
from django.core.signing import Signer
from django.db import models
from django.urls import reverse
from django.conf import settings

class File(models.Model):
    title = models.CharField(max_length=100)
    uploaded_by = models.CharField(max_length=100)
    document = models.FileField(upload_to='files/')
    signer = Signer(sep='/', salt='files.File')

    def __str__(self):
        return self.title

    # Override delete function to include deleting stored file
    def delete(self, *args, **kwargs):
        self.document.delete()
        super().delete(*args, **kwargs)

    def get_absolute_url(self):
        signed_pk = self.signer.sign(self.pk)
        path = reverse('file_transfer:single_file', kwargs={'signed_pk': signed_pk})
        url = f'{settings.SITE_URL}{path}'
        return url

fileTransfer/forms.py
from django import forms

from .models import File

class FileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ('title', 'uploaded_by', 'document')

fileTransfer/views.py
from django.views.generic import TemplateView, CreateView, ListView, DeleteView
from django.views import View
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.core.signing import BadSignature
from django.http import Http404
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import FileForm
from .models import File

# Class based view implementation
class Home(TemplateView):
    template_name = 'fileTransfer/home.html'

class FileUpload(LoginRequiredMixin, CreateView):
    model = File
    template_name = 'fileTransfer/upload.html'
    form_class = FileForm
    success_url = reverse_lazy('file_transfer:file_list')

class FileList(LoginRequiredMixin, ListView):
    model = File
    template_name = 'fileTransfer/file_list.html'
    context_object_name = 'files'

class SingleFile(LoginRequiredMixin, View):
    model = File
    template_name = 'fileTransfer/single_file.html'

    def get(self, request, signed_pk):
        try:
            pk = File.signer.unsign(signed_pk)
            single_file = File.objects.get(pk=pk)
        except (BadSignature, File.DoesNotExist):
            raise Http404('File doesn\'t exist.')

        return render(request, self.template_name, { 'single_file' : single_file })

    def post(self, request):
        pass

class DeleteFile(LoginRequiredMixin, DeleteView):
    model = File
    success_url = reverse_lazy('file_transfer:file_list')

class SignUp(View):
    form = UserCreationForm
    template_name = 'registration/signup.html'

    def get(self, request):
        form = self.form()
        return render(request, self.template_name, { 'form' : form })
    
    def post(self, request):
        form = self.form(request.POST)
        if form.is_valid():
            form.save()
            return redirect('file_transfer:login')
    
        return render(request, self.template_name, { 'form' : form })

# Function based view implementation

# Local file upload without reference in database
# def file_upload(request):
#     if request.method == 'POST':
#         uploaded_file = request.FILES['document']
#         fs = FileSystemStorage()
#         name = fs.save(uploaded_file.name, uploaded_file) # filename will auto-change if same file uploaded
#         url = fs.url(name)
#     return render(request, 'upload.html')

# File upload using form
# def file_upload(request):
#     if request.method == 'POST':
#         form = FileForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect('file_transfer:files_list')
#         else:
#             form = FileForm()
#     return render(request, 'upload.html', { 'form' : form })

# def file_list(request):
#     files = File.objects.all()
#     return render(request, 'fileTransfer/file_list.html', { 'files' : files })

fileTransfer/templates/fileTransfer/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'fileTransfer/main.css' %}">

    <title>File Transfer</title>
  </head>
  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
        <a class="navbar-brand" href="{% url 'file_transfer:home' %}">File Transfer</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button> 

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'file_transfer:home' %}">Home<span class="sr-only">(current)</span></a>
                </li>
                {% if user.is_authenticated %} 
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'file_transfer:file_list' %}">Files</a>
                    </li>  
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'file_transfer:upload' %}">Upload</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'file_transfer:password_change' %}">Change password</a>
                        <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'file_transfer:logout' %}">Logout</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'file_transfer:sign_up' %}">Sign up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'file_transfer:login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Content -->
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="card mb-4">
                    <div class="card-body">
                        {% block content %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <!-- Custom JS -->
    <script src="{% static 'fileTransfer/main.js' %}"></script>
  </body>
</html>

fileTransfer/templates/fileTransfer/file_list.html
{% extends 'fileTransfer/base.html' %}

{% block content %}
    <h1 class="mb-3">Files</h1>
    <p>
        <a href="{% url 'file_transfer:upload' %}" class="btn btn-primary mb-1">Upload file</a>
    </p>
    <table class="table mb-0">
        <thead>
            <tr>
                <th>Title</th>
                <th>Uploaded by</th>
                <th>Download</th>
                <th>Shareable link</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for file in files %}
            <tr>
                <td>{{ file.title }}</td>
                <td>{{ file.uploaded_by }}</td>
                <td>
                    <a href="{{ file.document.url }}" class="btn btn-primary btn-sm" download>
                        Download
                    </a>
                </td>
                <td>
                    <button class="btn btn-primary btn-sm" onclick="copyToClipboard('{{ file.get_absolute_url }}')">Copy link</button>
                </td>
                <td>
                    <form method="post" action="{% url 'file_transfer:delete_file' file.pk %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

fileTransfer/templates/fileTransfer/home.html
{% extends 'fileTransfer/base.html' %}

{% block content %}
    <h1 class="mb-3">Home</h1>
    <p>Welcome to the File Transfer site, {% if user.is_authenticated %}{{ user.username }}{% else %}visitor{% endif %}!</p>
{% endblock %}

fileTransfer/templates/fileTransfer/single_file.html
{% extends 'fileTransfer/base.html' %}

{% block content %}
    <h1 class="mb-3">Files</h1>
    <table class="table mb-0">
        <thead>
            <tr>
                <th>Title</th>
                <th>Uploaded by</th>
                <th>Download</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ single_file.title }}</td>
                <td>{{ single_file.uploaded_by }}</td>
                <td>
                    <a href="{{ single_file.document.url }}" class="btn btn-primary btn-sm" download>
                        Download
                    </a>
                </td>
            </tr>
        </tbody>
    </table>
{% endblock %}

fileTransfer/templates/fileTransfer/upload.html
{% extends 'fileTransfer/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <h1 class="mb-3">Upload</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary mt-2">Upload file</button>
    </form>
{% endblock %}